name: Build and test x16-PRos-libc

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup crosscompiler
      run: |
        sudo apt update
        sudo apt install build-essential -y
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo >> /home/runner/.bashrc
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        source /home/runner/.bashrc
        brew install i686-elf-gcc

    - name: Configure CMake
      run:  |
        echo $(which i686-elf-gcc)
        cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} CMAKE_C_COMPILER=$(which i686-elf-gcc)

    - name: Build
      run: cmake --build ${{github.workspace}}/build
